spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank accounts related PROD APIs"
  contactDetails:
    name: "Richard  - Product Owner"
    email: "richard@gmail.com"
  onCallSupport:
    - (555)354-2487
    - (555)971-9815