server:
  port: 8080

spring:
  application:
    name: accounts
  profiles:
    active: prod
  config:
    import: optional:configserver:http://localhost:8071/
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ""
  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  cloud:
    bus:
      destination: springCloudBus
      id: ${spring.application.name}:${random.uuid}
    stream:
      bindings:
        springCloudBusInput:
          group: accounts

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.cloud.bus: DEBUG
    org.springframework.cloud.stream: DEBUG